### ISSUE TITLE
Student code not displaying in grading interface when using Firefox

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/rs#379] opened 2023-10-04 15:45 UTC
**What Course are you in**
CS152HOFA2023

**What Page were you on**
Admin/Grading

**What is your username**
cigas

**Describe the bug**
When grading in Firefox, occasionally student code does not load into the grading interface. This happened about a month ago and again today. The images show that in Chrome a student has 6 saved versions of an assignment and shows the latest one. In the Firefox version, it looks like the student hasn't done anything. This applies to all students, not just the one shown in the images.

**Chrome:**
![Grading-Chrome](https://github.com/RunestoneInteractive/rs/assets/11619455/345c6fef-75fd-4b4f-8e72-98a4cb47ae96)

**Firefox:**
![Grading-Firefox](https://github.com/RunestoneInteractive/rs/assets/11619455/c8c5791c-f5c3-4fef-9d08-e615d1e38667)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by cigas** [comment] 2023-10-04 16:44
And it's worse. When I actually tried to run the code, which has unit tests, I get an error. Students were able to run this on Monday, Oct 2, but I can't now.

![Grading-Chrome-2](https://github.com/RunestoneInteractive/rs/assets/11619455/1b351555-bd86-4ef6-b9bc-c2a872533049)

**Comment by bnmnetp** [comment] 2023-10-04 17:24
Seems like it **might** be a caching problem... I can't reproduce it.  But I've heard from one other instructor about this.   I'm sure it still works for your students as I moved the assigments to a new server at the beginning of the Fall.

I have not rebuilt or updated thinkcspy since september 9, so this is really a mystery to me.

**Comment by cigas** [comment] 2023-10-04 18:03
September 9 might be about the time I first noticed it. This never happened to me before then.
I'll try clearing caches and using a different computer later tonight.

**Comment by bnmnetp** [comment] 2023-10-05 18:26
Nothing wrong with your unit tests, this is related to a change we made to support the ongoing work of a React version of a PreTeXt book.  We used to keep the activecode objects in `window.edList` but we needed to keep a list of ALL different components, so we changed `edList` to `componentMap`. This is one area that didn't get changed.  And although it is inconvenient for you, it doesn't change anything as the scores from the unit tests that are run from the grading interface are not saved anyway.  But it looks like it is keeping you from seeing what tests have passed.  Should be an easy fix...

**Comment by bnmnetp** [comment] 2023-10-08 19:42
The fix was easy but when I rebuilt the containers something weird happened that broke the server....  Even rolling back a week didn't fix the server so it is something outside of my control.  I did manage to find a workaround, but ... I'm a little nervous about deploying it without better internet and a bit more testing.

**Comment by bnmnetp** [comment] 2023-10-08 21:57
OK, this fix should be live....let me know.

**Comment by bnmnetp** [comment] 2023-10-18 18:04
closing this, as the fix has been live for a while now.

**Closed by bnmnetp** 2023-10-18 18:04 UTC
