### ISSUE TITLE
Unprocessable Request Error

### ISSUE THREAD

**Issue by mrunmayee2201** [RunestoneInteractive/rs#523] opened 2024-08-06 10:48 UTC
**What Course are you in**
Python 3 Programming
Knowing the course will help us a lot

**What Page were you on**
Assignment 1 Graded

**What is your username**
mrunmayeekhilare@gmail.com

**Describe the bug**
Status Code 422 popup when I try to do the assignment

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Error: Error: Unprocessable Request Detail: [object Object] Status Code: 422

**Comment by bnmnetp** [comment] 2024-08-06 20:52
There is no record of that email or username in our system.  The error that includes [object Object] also indicates to me that you are probably not on runestone.academy as the message should describe what parts of the request are missing.

**Comment by jainan** [comment] 2024-08-07 02:03
Even I am also facing the same error - 
POST https://py3.umsi.education/ns/logger/bookevent 422 (Unprocessable Content)
Error: Error: Unprocessable Request Detail: [object Object] Status Code: 422

What Course are you in 
Python 3 Programming Specialization

What Page were you on
Module 1 -> Programming in Python -> Assessment - Programming in Python
Module 1 -> Turtle Graphics -> Assessment - Turtle Graphics

What is your username
ankit.jain@chainthat.com

Describe the bug
Status Code 422 popup when I try to do the assignment

Traceback
If you got here through the Bug Report page and there was a stack trace, please paste it here

Javascript Errors
Error: Error: Unprocessable Request Detail: [object Object] Status Code: 422

[{…}]
0: input: -5.5
loc: (2) ['body', 'timezoneoffset']
msg: "Input should be a valid integer, got a number with a fractional part"
type: "int_from_float"
url: "https://errors.pydantic.dev/2.4/v/int_from_float"
[[Prototype]]: Object
length: 1
[[Prototype]]: Array(0)

**Comment by bnmnetp** [comment] 2024-08-07 12:03
It looks to me like you are either part of the coursera course or are at the University of Michigan.  In either case we don't have control over those servers and the version of the software they run.  Please report the problem to them.

@presnick, @mlhess -- I think you have some updating to do.

**Comment by mrunmayee2201** [comment] 2024-08-08 13:04
Please look into the issue ASAP, since many of us are losing our deadlines.

**Comment by presnick** [comment] 2024-08-08 13:11
Thank you for providing this information and for your patience.

I will post an update on the Coursera forums.

**Comment by bnmnetp** [comment] 2024-08-08 13:13
Since the problem is already fixed here, and @presnick is aware and working on the issue I'm going to close this.

**Closed by bnmnetp** 2024-08-08 13:13 UTC
